def func_18c3d71643f24487a0070e0ef9f29d00(cPDF):
    oPDF = cPDF()
    oPDF.header('1.7')
    oPDF.comment('âãÏÓ')
    oPDF.indirectobject(1, 0, '<<\n/Pages 2 0 R\n/Type /Catalog\n>>')
    oPDF.indirectobject(2, 0, '<<\n/Kids [3 0 R]\n/Count 1\n/Type /Pages\n>>')
    oPDF.indirectobject(3, 0, '<<\n/CropBox [4 0 R 5 0 R 6 0 R 7 0 R]\n/Parent 2 0 R\n/MediaBox [4 0 R 5 0 R 6 0 R 7 0 R]\n/Resources \n<<\n/Font \n<<\n/F1 8 0 R\n>>\n>>\n/Contents 9 0 R\n/Type /Page\n>>')
    oPDF.indirectobject(8, 0, '<<\n/BaseFont /Times-Roman\n/Subtype /Type1\n/Encoding /WinAnsiEncoding\n/Type /Font\n>>')
    oPDF.stream(9, 0, 'BT\n10 20 TD\n/F1 12 Tf\n(MediaBox and CropBox with indirect objects.) Tj\nET', '<<\n/Length %d\n>>')
    oPDF.indirectobject(4, 0, '0')
    oPDF.indirectobject(5, 0, '0')
    oPDF.indirectobject(6, 0, '250')
    oPDF.indirectobject(7, 0, '50')
    oPDF.xrefAndTrailer('1 0 R')
    return oPDF.sample()
