def func_dbd76bdc035846059324fe7c7ae7dcb5(cPDF):
    oPDF = cPDF()
    oPDF.header('1.4')
    oPDF.indirectobject(1, 0, '<<\r\n\t/Type /Catalog\r\n\t/Pages 2 0 R\r\n>>')
    oPDF.indirectobject(2, 0, '<<\r\n\t/Type /Pages\r\n\t/Kids [3 0 R]\r\n\t/Count 1\r\n>>')
    oPDF.indirectobject(3, 0, '<<\r\n\t/Parent 2 0 R \r\n\t/Contents 6 0 R \r\n\t/MediaBox [0 0 612 792 ]\r\n\t/Resources << \r\n\t\t/Font <</F1 5 0 R>>\r\n\t\t>>\r\n\t/Type /Page \r\n>>')
    oPDF.indirectobject(4, 0, '<<\r\n\t/ColorSpace /DeviceCMYK\r\n\t/Coords [0 0 290 0]\r\n\t/ShadingType 2\r\n\t/Function 5 0 R\r\n>>')
    oPDF.indirectobject(5, 0, '<<\r\n\t/Type /Font\r\n\t/Subtype /Type1\r\n\t/BaseFont /Helvetica\r\n>>')
    oPDF.stream(6, 0, '0 0 0 1 k\r\nBT /F1 25 Tf 100 680 TD\r\n(ColorSpace: Device)Tj\r\n1 0 0 0 k\r\n(C)Tj\r\n0 1 0 0 k\r\n(M)Tj\r\n0 0 1 0 k\r\n(Y)Tj\r\n0 0 0 1 k\r\n(K)Tj\r\nET', '<<\r\n>>')
    oPDF.xrefAndTrailer('1 0 R')
    return oPDF.sample()
